### ISSUE TITLE
event to select voice

### ISSUE THREAD

**Issue by yoshuawuyts** [YerkoPalma/choo-tts#1]
I was hacking on a TTS project with a friend today, and it's been really fun! — got a bit of feedback tho:

Right now it's a bit awkward to select a new voice — it involves looking up properties, and finding the `indexOf` property. It'd be cool if we could emit an event to change the voice, and it'd return a boolean of something to signal if it was successful.

Thanks! :grin:

**Comment by YerkoPalma** [comment]
You mean something like this?

```js
emit('tts:setVoice', newVoice)
```

If that's the case, what would be the `newVoice` object? a Voice object? a string with the name of the voice?
Also, notice that voices depend on the system, so if you set a voice to something not supported by the client system shoult it throw?

**Comment by yoshuawuyts** [comment]
I was thinking a string might be simplest. Also perhaps emit an error if
trying to set an unsupported voice

**Comment by YerkoPalma** [comment]
Fair enough. Will work on it when I got time (or if you have something, you can send a PR :))
